# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: npm
    directory: "/discord-bot"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: "/netlify-functions-ecommerce"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: "/photography-site-demo.js"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: "/typescript-express-reviews"
    schedule:
      interval: "weekly"
